# Custom Language File for Launcher Customizer

[ejs.app]
title = "NUSUSMP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Haiilyyy"
mediaTwitterURL = "https://twitter.com/haiilyyy_"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/"

[ejs.settings]
sourceGithubLink = "https://github.com/Haiilyyy"
supportLink = "https://discord.gg/"

[ejs.welcome]
welcomeHeader = "WELCOME TO NUSUSMP"
welcomeDescription = "Welcome description."
welcomeDescCTA = "You are just a few clicks away from NUSUSMP."
